export const TASKS = [
  {
    id: '1',
    title: 'Angular',
    description:
      'Get overview of Angular by completing assignments, attending lectures and asking questions',
    completed: false,
    assigned: ['Shannon', 'Tim', 'Wes', 'Corey', 'Julio']
  },
  {
    id: '2',
    title: 'Grocery Shopping',
    description:
      'Taco Tuesdays - pickup lettuce, tomatoes, cheese, soft shells, hamburger meat, salsa',
    completed: false,
    assigned: ['Shannon', 'Mike', 'Courtney', 'Kate']
  },
  {
    id: '3',
    title: 'Pay Cable Bill',
    description: '',
    completed: false,
    assigned: ['Mike', 'Donna', 'Matthew S']
  },
  {
    id: '4',
    title: 'Walk in the Park',
    description: 'Take a break from studies and get some fresh air at the park',
    completed: false,
    assigned: ['Shannon', 'Wes', 'Cody', 'Michael H']
  },
  {
    id: '5',
    title: 'Book Shopping',
    description:
      'Mastering Python, The Complete Guide to Angular, Serpents of Venice',
    completed: true,
    assigned: ['Shannon', 'Aidan', 'Michael W']
  },
  {
    id: '6',
    title: 'Starbucks run',
    description: 'Pick up a Venti Black Eye and Venti Cafe Verona Pour Over',
    completed: false,
    assigned: ['Stephanie', 'Kelsey', 'Ryan']
  },
  {
    id: '7',
    title: 'Beach Supplies',
    description: 'Stop by Walgreens and pick up some sunscreen and baby powder',
    completed: false,
    assigned: ['Shannon', 'Stephanie', 'Faith', 'Paul', 'Rashawnda']
  },
  {
    id: '8',
    title: 'Laundry',
    description: 'need to wash towels and darks',
    completed: false,
    assigned: ['Shannon', 'Faith', 'Sitry', 'Samrat']
  },
  {
    id: '9',
    title: 'Mow the grass',
    description: 'self explanatory',
    completed: false,
    assigned: ['Mike', 'Will', 'Hollis', 'Matthew B']
  },
  {
    id: '10',
    title: 'Recycling',
    description: 'self explanatory',
    completed: false,
    assigned: ['Mike', 'Shannon', 'Deborah', 'Sebastian']
  }
];
